/**
 * Filter Module - Autofill Select Options
 * Automatically populate select filter fields with available options from list items
 */

import { getInstance } from './filters';
import { getItemFieldValue } from './filters';
import { getCache } from './cache';

/**
 * Get all unique values for a field from a single list's items
 */
function getUniqueFieldValuesFromList(
  listElement: HTMLElement,
  field: string,
  instance: string | null
): string[] {
  const cache = getCache(instance, listElement);
  const values = new Set<string>();

  cache.items.forEach((item) => {
    const itemValues = getItemFieldValue(item, field);
    itemValues.forEach((value) => {
      if (value) {
        values.add(value);
      }
    });
  });

  return Array.from(values);
}

/**
 * Get all unique values for a field from all lists matching the instance
 */
function getUniqueFieldValuesFromAllLists(
  listElements: NodeListOf<Element> | HTMLElement[],
  field: string,
  instance: string | null
): string[] {
  const allValues = new Set<string>();
  const elements = Array.from(listElements) as HTMLElement[];

  elements.forEach((listElement) => {
    getUniqueFieldValuesFromList(listElement, field, instance).forEach((value) =>
      allValues.add(value)
    );
  });

  return Array.from(allValues).sort();
}

/**
 * Autofill select element with options from list items
 */
export function autofillSelect(selectElement: HTMLSelectElement): void {
  const field = selectElement.dataset.filterField;
  if (!field) return;

  // Check if autofill is enabled (must be explicitly set to "true")
  const autofillEnabled = selectElement.dataset.filterAutofill === 'true';
  if (!autofillEnabled) return;

  // Check if already populated (unless data-filter-autofill-refresh is set)
  const hasOptions = selectElement.options.length > 0;
  const shouldRefresh = selectElement.dataset.filterAutofillRefresh === 'true';
  if (hasOptions && !shouldRefresh) {
    // Check if options look auto-generated (all have data-filter-autofill-option attribute)
    const firstOption = selectElement.options[0];
    const isAutoGenerated = firstOption?.dataset.filterAutofillOption === 'true';
    if (isAutoGenerated) {
      // Already auto-generated, refresh if needed
      if (shouldRefresh) {
        // Clear auto-generated options
        Array.from(selectElement.options).forEach((option) => {
          if (option.dataset.filterAutofillOption === 'true') {
            option.remove();
          }
        });
      } else {
        return; // Don't regenerate
      }
    } else {
      return; // Has manual options, don't overwrite
    }
  }

  // Find all list elements for this instance (e.g. all accordion months)
  const instance = getInstance(selectElement);
  const baseListSelector = '[data-filter-list]';
  const listSelector = instance
    ? `[data-filter-instance="${instance}"] ${baseListSelector}, ${baseListSelector}[data-filter-instance="${instance}"]`
    : `${baseListSelector}:not([data-filter-instance])`;

  const listElements = document.querySelectorAll(listSelector);
  if (listElements.length === 0) return;

  // Get unique values from all lists (not just the first)
  const values = getUniqueFieldValuesFromAllLists(listElements, field, instance);
  if (values.length === 0) return;

  // Get "All" option configuration
  const allValue = selectElement.dataset.filterAllValue || '';
  const allText = selectElement.dataset.filterAllText || 'All';
  const includeAll = selectElement.dataset.filterAutofillAll !== 'false';

  // Clear existing auto-generated options
  if (hasOptions) {
    Array.from(selectElement.options).forEach((option) => {
      if (option.dataset.filterAutofillOption === 'true') {
        option.remove();
      }
    });
  } else {
    // Clear all if empty
    selectElement.innerHTML = '';
  }

  // Add "All" option if enabled
  if (includeAll) {
    const allOption = document.createElement('option');
    allOption.value = allValue;
    allOption.textContent = allText;
    allOption.dataset.filterAutofillOption = 'true';
    selectElement.appendChild(allOption);
  }

  // Add options for each unique value
  values.forEach((value) => {
    const option = document.createElement('option');
    option.value = value;
    // Use capitalized version for display, or the value itself
    option.textContent = value
      .split(' ')
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
    option.dataset.filterAutofillOption = 'true';
    selectElement.appendChild(option);
  });
}

/**
 * Initialize autofill for all select elements with data-filter-autofill="true"
 */
export function initializeAutofill(): void {
  // Find all select elements that should be autofilled
  document.querySelectorAll('select[data-filter-field]').forEach((select) => {
    const el = select as HTMLSelectElement;
    
    // Autofill must be explicitly enabled via data-filter-autofill="true"
    const autofillEnabled = el.dataset.filterAutofill === 'true';
    if (autofillEnabled) {
      autofillSelect(el);
    }
  });
}

/**
 * Refresh autofill for a specific instance
 */
export function refreshAutofill(instance: string | null): void {
  const baseSelector = 'select[data-filter-field]';
  const selector = instance
    ? `[data-filter-instance="${instance}"] ${baseSelector}, ${baseSelector}[data-filter-instance="${instance}"]`
    : `${baseSelector}:not([data-filter-instance])`;

  document.querySelectorAll(selector).forEach((select) => {
    const el = select as HTMLSelectElement;
    const autofillEnabled = el.dataset.filterAutofill === 'true';
    if (autofillEnabled) {
      autofillSelect(el);
    }
  });
}
